---
- name: Proxmox Rollback VM(s)
  hosts: localhost
  gather_facts: false

  vars:
    # proxmox_cluster_host: "proxmox-cluster-host"
    # proxmox_target_node: "proxmox-node"
    vm_guests_to_rollback: ["vm-test-001", "vm-test-002"]
    snapshot: "SNAPSHOT_TESTING"
    start_after_rollback: false

  # vars_prompt:
  #   - name: proxmox_api_user
  #     prompt: "Proxmox API User"
  #     default: "root@pam"
  #     private: false

  #   - name: proxmox_api_secret
  #     prompt: "Proxmox API Secret"
  #     unsafe: true
  #     private: true
  #     confirm: true

  tasks:
    - name: Rollback the VM(s) to '{{ snapshot }}'
      community.general.proxmox_snap:
        # api_user: "{{ proxmox_api_user }}"
        # api_password: "{{ proxmox_api_secret }}"
        # api_host: "{{ proxmox_cluster_host }}"
        hostname: "{{ item }}"
        snapname: "{{ snapshot }}"
        state: "rollback"
        timeout: 600
      with_items: "{{ vm_guests_to_rollback }}"
      register: rollback_vm_results
      async: 600
      poll: 0

    - name: Wait for all VM(s) to be rolledback
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: vm_rollback_job_result
      until: vm_rollback_job_result.finished
      retries: 300
      delay: 5
      with_items: "{{ rollback_vm_results.results }}"

    - name: Start the VM(s)
      community.general.proxmox_kvm:
        # api_user: "{{ proxmox_api_user }}"
        # api_password: "{{ proxmox_api_secret }}"
        # api_host: "{{ proxmox_cluster_host }}"
 #       node: "{{ proxmox_target_node }}"
        name: "{{ item }}"
        state: "started"
        timeout: 600
      with_items: "{{ vm_guests_to_rollback }}"
      register: start_vm_results
      async: 600
      poll: 0
      when: start_after_rollback

    - name: Wait for all VM(s) to start
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: vm_start_job_result
      until: vm_start_job_result.finished
      retries: 300
      delay: 5
      with_items: "{{ start_vm_results.results }}"
      when: start_after_rollback
